### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by duramato** [comment]
When should i expect to see this in a release? Is there any release schedule?

**Comment by PeterDaveHello** [comment]
@leonsoft-kras can we schedule another release for this? Don't know what's your expected release lifecycle.

**Comment by leonsoft-kras** [comment]
I propose to update the program:
- Immediately if a serious error is detected
- Not more than 2-3 weeks, if there is a change.

ok?

**Comment by PeterDaveHello** [comment]
@leonsoft-kras so having new releases every 2~3 weeks would be fine, right?

**Comment by leonsoft-kras** [comment]
Yes
and 
immediately, if a serious bug is detected.

**Comment by PeterDaveHello** [comment]
Okay so @duramato we'll have another release next week.

**Comment by PeterDaveHello** [comment]
@duramato I released v5.8.2 here: https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.8.2, not sure which platform you're using right now, the Windows release will need @leonsoft-kras's help.

**Comment by duramato** [comment]
Thanks @PeterDaveHello

**Pull request merged**
